DGtal: DGtal::RestrictedImage< TDomain, TImageContainer > Class Template Reference
DGtal::RestrictedImage< TDomain, TImageContainer > Class Template Reference
#include <RestrictedImage.h>
Public Types
typedef RestrictedImage
< TDomain, TImageContainer > Self
typedef TImageContainer ImageContainer
typedef TImageContainer::Point Point
typedef TImageContainer::Value Value
typedef TImageContainer * ImagePointer
typedef TDomain Domain
typedef DefaultConstImageRange
< Self > ConstRange
typedef DefaultImageRange< Self > Range
Public Member Functions
BOOST_CONCEPT_ASSERT ((CImage< TImageContainer >))
BOOST_CONCEPT_ASSERT ((CDomain< TDomain >))
BOOST_STATIC_ASSERT (TDomain::Space::dimension==TImageContainer::Domain::Space::dimension)
BOOST_STATIC_ASSERT ((boost::is_same< typename TDomain::Point, typename TImageContainer::Point >::value))
RestrictedImage (const Domain &aDomain, ImageContainer &anImage)
RestrictedImage & operator= (const RestrictedImage &other)
~RestrictedImage ()
const Domain & domain () const
ConstRange constRange () const
Range range ()
Value operator() (const Point &aPoint) const
void setValue (const Point &aPoint, const Value &aValue)
void selfDisplay (std::ostream &out) const
bool isValid () const
const ImageContainer * getPointer () const
Protected Attributes
ImagePointer myImagePointer
Domain mySubDomain
Private Member Functions
RestrictedImage ()
Detailed Description
template<typename TDomain, typename TImageContainer>
class DGtal::RestrictedImage< TDomain, TImageContainer >
Aim: implements a restricted image with a given domain (i.e. a subdomain).
Description of template class 'RestrictedImage'
This class is (like Image class) a lightweight proxy on ImageContainers (models of CImage). It uses a given Domain (i.e. a subdomain) but work directly (for read and write) thanks to an alias (i.e. a pointer) on the original ImageContainer in argument. RestrictedImage class is also a model of CImage.
Caution :
RestrictedImage Domain Space dimension must be the same than the original ImageContainer Domain Space dimension,
the type of value of Point for the RestrictedImage Domain must also be the same than the type of value of Point for the original ImageContainer.
Template Parameters:
TDomain a domain.
TImageContainer an image container type (model of CImage).
Definition at line 80 of file RestrictedImage.h.
Member Typedef Documentation
template<typename TDomain, typename TImageContainer> typedef DefaultConstImageRange<Self> DGtal::RestrictedImage< TDomain, TImageContainer >::ConstRange
Definition at line 104 of file RestrictedImage.h.
template<typename TDomain, typename TImageContainer> typedef TDomain DGtal::RestrictedImage< TDomain, TImageContainer >::Domain
Definition at line 102 of file RestrictedImage.h.
template<typename TDomain, typename TImageContainer> typedef TImageContainer DGtal::RestrictedImage< TDomain, TImageContainer >::ImageContainer
Types copied from the container.
Definition at line 95 of file RestrictedImage.h.
template<typename TDomain, typename TImageContainer> typedef TImageContainer* DGtal::RestrictedImage< TDomain, TImageContainer >::ImagePointer
Pointer to the image container data.
Definition at line 100 of file RestrictedImage.h.
template<typename TDomain, typename TImageContainer> typedef TImageContainer::Point DGtal::RestrictedImage< TDomain, TImageContainer >::Point
Definition at line 96 of file RestrictedImage.h.
template<typename TDomain, typename TImageContainer> typedef DefaultImageRange<Self> DGtal::RestrictedImage< TDomain, TImageContainer >::Range
Definition at line 105 of file RestrictedImage.h.
template<typename TDomain, typename TImageContainer> typedef RestrictedImage<TDomain,TImageContainer> DGtal::RestrictedImage< TDomain, TImageContainer >::Self
Definition at line 86 of file RestrictedImage.h.
template<typename TDomain, typename TImageContainer> typedef TImageContainer::Value DGtal::RestrictedImage< TDomain, TImageContainer >::Value
Definition at line 97 of file RestrictedImage.h.
Constructor & Destructor Documentation
template<typename TDomain, typename TImageContainer> DGtal::RestrictedImage< TDomain, TImageContainer >::RestrictedImage (const Domain & aDomain, ImageContainer & anImage) inline
Definition at line 111 of file RestrictedImage.h.
References DGtal::trace, and DGtal::Trace::warning().
                                                                   :
            mySubDomain(aDomain), myImagePointer(&anImage)
    {
#ifdef DEBUG_VERBOSE
        trace.warning() << "RestrictedImage Ctor fromRef "<<std::endl;
#endif
}
template<typename TDomain, typename TImageContainer> DGtal::RestrictedImage< TDomain, TImageContainer >::~RestrictedImage () inline
Destructor. Does nothing
Definition at line 141 of file RestrictedImage.h.
{}
template<typename TDomain, typename TImageContainer> DGtal::RestrictedImage< TDomain, TImageContainer >::RestrictedImage () inline private
Default constructor.
Definition at line 252 of file RestrictedImage.h.
References DGtal::trace, and DGtal::Trace::warning().
                      {
#ifdef DEBUG_VERBOSE
        trace.warning() << "RestrictedImage Ctor default "<<std::endl;
#endif
    }
Member Function Documentation
template<typename TDomain, typename TImageContainer> DGtal::RestrictedImage< TDomain, TImageContainer >::BOOST_CONCEPT_ASSERT ((CImage< TImageContainer >))
Checking concepts.
template<typename TDomain, typename TImageContainer> DGtal::RestrictedImage< TDomain, TImageContainer >::BOOST_CONCEPT_ASSERT ((CDomain< TDomain >))
template<typename TDomain, typename TImageContainer> DGtal::RestrictedImage< TDomain, TImageContainer >::BOOST_STATIC_ASSERT (TDomain::Space::dimension = =TImageContainer::Domain::Space::dimension)
template<typename TDomain, typename TImageContainer> DGtal::RestrictedImage< TDomain, TImageContainer >::BOOST_STATIC_ASSERT ((boost::is_same< typename TDomain::Point, typename TImageContainer::Point >::value))
template<typename TDomain, typename TImageContainer> ConstRange DGtal::RestrictedImage< TDomain, TImageContainer >::constRange () const inline
Returns the range of the underlying image to iterate over its values
Returns:
a range.
Definition at line 164 of file RestrictedImage.h.
    {
        return ConstRange( *this );
    }
template<typename TDomain, typename TImageContainer> const Domain& DGtal::RestrictedImage< TDomain, TImageContainer >::domain () const inline
Returns a reference to the underlying image domain.
Returns:
a reference to the domain.
Definition at line 153 of file RestrictedImage.h.
References DGtal::RestrictedImage< TDomain, TImageContainer >::mySubDomain.
Referenced by DGtal::RestrictedImage< TDomain, TImageContainer >::operator()(), and DGtal::RestrictedImage< TDomain, TImageContainer >::setValue().
    {
        return mySubDomain;
    }
template<typename TDomain, typename TImageContainer> const ImageContainer* DGtal::RestrictedImage< TDomain, TImageContainer >::getPointer () const inline
Returns the pointer on the Image container data.
Returns:
a const ImagePointer.
Definition at line 242 of file RestrictedImage.h.
References DGtal::RestrictedImage< TDomain, TImageContainer >::myImagePointer.
    {
        return myImagePointer;
    }
template<typename TDomain, typename TImageContainer> bool DGtal::RestrictedImage< TDomain, TImageContainer >::isValid () const inline
Checks the validity/consistency of the object.
Returns:
'true' if the object is valid, 'false' otherwise.
the validity of the Image
Definition at line 232 of file RestrictedImage.h.
References DGtal::RestrictedImage< TDomain, TImageContainer >::myImagePointer.
    {
        return (myImagePointer->isValid() );
    }
template<typename TDomain, typename TImageContainer> Value DGtal::RestrictedImage< TDomain, TImageContainer >::operator() (const Point & aPoint) const inline
Get the value of an image at a given position given by a Point.
Precondition:
the point must be in the domain
Parameters:
aPoint the point.
Returns:
the value at aPoint.
Definition at line 192 of file RestrictedImage.h.
References DGtal::RestrictedImage< TDomain, TImageContainer >::domain(), and DGtal::RestrictedImage< TDomain, TImageContainer >::myImagePointer.
    {
        ASSERT(this->domain().isInside(aPoint));
        return myImagePointer->operator()(aPoint);
    }
template<typename TDomain, typename TImageContainer> RestrictedImage& DGtal::RestrictedImage< TDomain, TImageContainer >::operator= (const RestrictedImage< TDomain, TImageContainer > & other) inline
Assignment.
Parameters:
other the object to copy.
Returns:
a reference on 'this'.
Definition at line 124 of file RestrictedImage.h.
References DGtal::RestrictedImage< TDomain, TImageContainer >::myImagePointer, DGtal::trace, and DGtal::Trace::warning().
    {
#ifdef DEBUG_VERBOSE
        trace.warning() << "RestrictedImage assignment "<<std::endl;
#endif
        if (&other != this)
        {
            myImagePointer = other.myImagePointer;
        }
        return *this;
    }
template<typename TDomain, typename TImageContainer> Range DGtal::RestrictedImage< TDomain, TImageContainer >::range () inline
Returns the range of the underlying image to iterate over its values
Returns:
a range.
Definition at line 175 of file RestrictedImage.h.
    {
        return Range( *this );
    }
template<typename TD , typename TIC > void DGtal::RestrictedImage< TD, TIC >::selfDisplay (std::ostream & out) const inline
Writes/Displays the object on an output stream.
Parameters:
out the output stream where the object is written.
Definition at line 57 of file RestrictedImage.ih.
{
    out << "[RestrictedImage] "<< myImagePointer ;
}
template<typename TDomain, typename TImageContainer> void DGtal::RestrictedImage< TDomain, TImageContainer >::setValue (const Point & aPoint, const Value & aValue) inline
Set a value on an Image at a position specified by a Point.
Precondition:
it must be a point in the image domain.
Parameters:
aPoint the point.
aValue the value.
Definition at line 209 of file RestrictedImage.h.
References DGtal::RestrictedImage< TDomain, TImageContainer >::domain(), and DGtal::RestrictedImage< TDomain, TImageContainer >::myImagePointer.
    {
        ASSERT(this->domain().isInside(aPoint));
        myImagePointer->setValue(aPoint,aValue);
    }
Field Documentation
template<typename TDomain, typename TImageContainer> ImagePointer DGtal::RestrictedImage< TDomain, TImageContainer >::myImagePointer protected
Owning pointer on the image container.
Definition at line 262 of file RestrictedImage.h.
Referenced by DGtal::RestrictedImage< TDomain, TImageContainer >::getPointer(), DGtal::RestrictedImage< TDomain, TImageContainer >::isValid(), DGtal::RestrictedImage< TDomain, TImageContainer >::operator()(), DGtal::RestrictedImage< TDomain, TImageContainer >::operator=(), and DGtal::RestrictedImage< TDomain, TImageContainer >::setValue().
template<typename TDomain, typename TImageContainer> Domain DGtal::RestrictedImage< TDomain, TImageContainer >::mySubDomain protected
The image SubDomain
Definition at line 267 of file RestrictedImage.h.
Referenced by DGtal::RestrictedImage< TDomain, TImageContainer >::domain().
The documentation for this class was generated from the following files:
RestrictedImage.h
RestrictedImage.ih